#! /bin/bash

set -u

if [ "$(id -u)" != "0" ] && ! (groups | grep docker >/dev/null 2>&1) ; then
  echo "Requires sudo or be in docker group" >&2
  exit 1
fi
main_dir=$(dirname $(readlink -f $0))
env_file="${env_file:-${main_dir}/build_run_env.sh}"
# Set variables common in docker build and run
source $env_file

for _x in HOME_DIR in_dir out_dir ; do
  _dir=$(eval echo "\${$_x}")
  if [ -z "$_dir" ] || [ ! -d "$_dir" ]; then
    echo "Required directory ${_x} not defined or invalid."
    exit 1
  fi
done

cat <<EOT >$main_dir/start.sh
#! /bin/bash

# Uncomment to debug
set -eux

export GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins/1.11
export PATH=\$PATH:/home/$APPUSER/meteosatlib-1.3/examples

PRODUCTS="\${PRODUCTS:-EnhancedIr}"
FORMAT="\${FORMAT:-JPEG}"
TIMESTR=${TIMESTR:-\$(/main/get_timestr.py)}

temp_dir=/tmp/out/$RANDOM
mkdir \$temp_dir || {
  echo "Can't create working directory \$temp_dir" >&2
  exit 1
}
trap "rm -rf \$temp_dir" EXIT SIGHUP SIGINT SIGTERM

cd /tmp/out

msat --Area=10,-50,60,10 --conv GTiff /tmp/in/$MSAT_INPUT_FILE

EOT
chmod 755 $main_dir/start.sh

docker run -i -t --rm \
-e TIMESTR="${TIMESTR:-}" \
-e $MSAT_INPUT_FILE=$MSAT_INPUT_FILE \
-v $HOME_DIR:/home/$APPUSER \
-v $main_dir:/main \
-v $in_dir:/tmp/in \
-v $out_dir:/tmp/out \
$REPO_NAME:$REPO_TAG $*


